//https://betterprogramming.pub/create-a-letter-picture-like-google-with-react-ae12a7a4390e
// https://github.com/danilo95/letter-picture-like-Google-with-React

export const  getRandomColor=()=> {
    var letters = "0123456789ABCDEF";
    var color = "#";
    for (var i = 0; i < 6; i++) {
      color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
  }


  const getInitials = (name) => {
    let initials;
    const nameSplit = name.split(" ");
    const nameLength = nameSplit.length;
    if (nameLength > 1) {
        initials =
            nameSplit[0].substring(0, 1) +
            nameSplit[nameLength - 1].substring(0, 1);
    } else if (nameLength === 1) {
        initials = nameSplit[0].substring(0, 1);
    } else return;

    return initials.toUpperCase();
};

export const createImageFromInitials = (size, name, color) => {
    if (name == null) return;
    name=getInitials(name)

    const canvas=document.createElement("canvas")
    const context=canvas.getContext("2d")
    canvas.width=canvas.height=size

    context.fillStyle="#ffffff"
    context.fillRect(0,0,size,size)

    context.fillStyle=`${color}50`
    context.fillRect(0,0,size,size)

    context.fillStyle="#FFFFFF";
    context.textBaseline="middle"
    context.textAlign="center"
    context.font =`${size/2}px Roboto`
    context.fillText(name,(size/2),(size/2))

    return canvas.toDataURL()
};

export const formatDate = (rawDate) => {
  let time = rawDate.split('T')[1].split(':')
  let hours = time[0]

  let amPM = hours.slice(0,2) < 12 ? "AM" : "PM"

  let formattedTime = hours.slice(0,2) > 12 ? String(hours.slice(0,2) - 12) : String(hours.slice(0,2))
  formattedTime = formattedTime.length === 1 ? "0" + formattedTime + ":" + time[1] : formattedTime + ":" + time[1]
  formattedTime = formattedTime + amPM

  let formattedDate = rawDate.split('T')[0].split('-')
  formattedDate = formattedDate[1] + '/' + formattedDate[2] + '/' + formattedDate[0]

  return {formattedTime, formattedDate}
}

export const cities = ["Acton",
"Adelanto",
"Agoura Hills",
"Alameda",
"Alamo",
"Albany",
"Alhambra",
"Aliso Viejo",
"Alpaugh",
"Alpine",
"Altadena",
"Alturas",
"American Canyon",
"Anaheim",
"Anderson",
"Angwin",
"Antioch",
"Apple Valley",
"Aptos",
"Arbuckle",
"Arcadia",
"Arcata",
"Armona",
"Arnold",
"Aromas",
"Arroyo Grande",
"Artesia",
"Arvin",
"Atascadero",
"Atherton",
"Atwater",
"Auberry",
"Auburn",
"Avalon",
"Avenal",
"Avery",
"Azusa",
"Bakersfield",
"Baldwin Park",
"Banning",
"Barstow",
"Beale Afb",
"Beaumont",
"Beckwourth",
"Bell Gardens",
"Bell",
"Bellflower",
"Belmont",
"Ben Lomond",
"Benicia",
"Berkeley",
"Bethel Island",
"Beverly Hills",
"Big Bear City",
"Big Bear Lake",
"Big Pine",
"Biggs",
"Biola",
"Bishop",
"Bloomington",
"Blue Lake",
"Blythe",
"Bodega Bay",
"Bodfish",
"Bolinas",
"Bonita",
"Bonsall",
"Boron",
"Borrego Springs",
"Boulder Creek",
"Boyes Hot Springs",
"Brawley",
"Brea",
"Brentwood",
"Brisbane",
"Buellton",
"Buena Park",
"Burbank",
"Burlingame",
"Burney",
"Buttonwillow",
"Byron",
"Cabazon",
"Calabasas",
"Calexico",
"California City",
"Calimesa",
"Calipatria",
"Calistoga",
"Camarillo",
"Cambria",
"Campbell",
"Cantua Creek",
"Capitola",
"Carlsbad",
"Carmel By The Sea",
"Carmichael",
"Carpinteria",
"Carson",
"Caruthers",
"Castro Valley",
"Castroville",
"Cathedral City",
"Cayucos",
"Ceres",
"Cerritos",
"Chester",
"Chico",
"Chino Hills",
"Chino",
"Chowchilla",
"Chualar",
"Chula Vista",
"Citrus Heights",
"Claremont",
"Clayton",
"Clearlake Oaks",
"Clearlake",
"Cloverdale",
"Clovis",
"Coachella",
"Coalinga",
"Cobb",
"Colfax",
"Colton",
"Columbia",
"Colusa",
"Compton",
"Concord",
"Copperopolis",
"Corcoran",
"Corning",
"Corona",
"Coronado",
"Corte Madera",
"Costa Mesa",
"Cotati",
"Cottonwood",
"Covelo",
"Covina",
"Crescent City",
"Crescent Mills",
"Crestline",
"Crockett",
"Culver City",
"Cupertino",
"Cutler",
"Cutten",
"Cypress",
"Daly City",
"Dana Point",
"Danville",
"Davis",
"Deer Park",
"Del Mar",
"Del Rey",
"Delano",
"Delhi",
"Denair",
"Desert Hot Springs",
"Diablo",
"Diamond Bar",
"Diamond Springs",
"Dillon Beach",
"Dinuba",
"Dixon",
"Dorris",
"Dos Palos",
"Downey",
"Duarte",
"Dublin",
"Ducor",
"Dunsmuir",
"Durham",
"Earlimart",
"El Cajon",
"El Centro",
"El Cerrito",
"El Dorado Hills",
"El Granada",
"El Monte",
"El Segundo",
"El Sobrante",
"El Verano",
"Eldridge",
"Elk Grove",
"Elmira",
"Emeryville",
"Empire",
"Encinitas",
"Escalon",
"Escondido",
"Esparto",
"Etna",
"Eureka",
"Exeter",
"Fair Oaks",
"Fairfax",
"Fairfield",
"Fall River Mills",
"Fallbrook",
"Farmersville",
"Farmington",
"Felton",
"Ferndale",
"Fillmore",
"Firebaugh",
"Folsom",
"Fontana",
"Foothill Ranch",
"Foresthill",
"Forestville",
"Fort Bragg",
"Fort Jones",
"Fortuna",
"Fountain Valley",
"Fowler",
"Frazier Park",
"Freedom",
"Fremont",
"French Camp",
"French Gulch",
"Fresno",
"Friant",
"Fullerton",
"Galt",
"Garden Grove",
"Gardena",
"Georgetown",
"Gilroy",
"Glen Ellen",
"Glendale",
"Glendora",
"Goleta",
"Gonzales",
"Goshen",
"Grand Terrace",
"Granite Bay",
"Grass Valley",
"Graton",
"Greenfield",
"Greenville",
"Grenada",
"Gridley",
"Grover Beach",
"Guadalupe",
"Guerneville",
"Gustine",
"Hacienda Heights",
"Half Moon Bay",
"Hamilton City",
"Hanford",
"Hawaiian Gardens",
"Hawthorne",
"Hayfork",
"Hayward",
"Healdsburg",
"Heber",
"Hemet",
"Hercules",
"Hermosa Beach",
"Hesperia",
"Hickman",
"Highland",
"Hollister",
"Holtville",
"Homeland",
"Hornbrook",
"Hughson",
"Huntington Beach",
"Huntington Park",
"Huron",
"Hydesville",
"Imperial Beach",
"Imperial",
"Independence",
"Indian Wells",
"Indio",
"Inglewood",
"Inverness",
"Inyokern",
"Ione",
"Irvine",
"Isleton",
"Ivanhoe",
"Jackson",
"Jamestown",
"Jamul",
"Joshua Tree",
"Julian",
"Keene",
"Kelseyville",
"Kentfield",
"Kerman",
"Kernville",
"Kettleman City",
"Keyes",
"King City",
"Kings Beach",
"Kingsburg",
"Klamath",
"Knightsen",
"La Canada Flintridge",
"La Habra",
"La Mesa",
"La Mirada",
"La Palma",
"La Puente",
"La Quinta",
"La Verne",
"Lafayette",
"Laguna Beach",
"Laguna Hills",
"Laguna Niguel",
"Lake Arrowhead",
"Lake Elsinore",
"Lake Forest",
"Lake Isabella",
"Lakeport",
"Lakeside",
"Lakewood",
"Lamont",
"Lancaster",
"Larkspur",
"Lathrop",
"Laton",
"Lawndale",
"Laytonville",
"Le Grand",
"Lebec",
"Lemon Cove",
"Lemon Grove",
"Lemoore",
"Lewiston",
"Lincoln",
"Linden",
"Lindsay",
"Littlerock",
"Live Oak",
"Livermore",
"Livingston",
"Lockeford",
"Lodi",
"Loma Linda",
"Lomita",
"Lompoc",
"Lone Pine",
"Long Beach",
"Loomis",
"Los Alamitos",
"Los Alamos",
"Los Altos",
"Los Angeles",
"Los Banos",
"Los Gatos",
"Los Molinos",
"Lost Hills",
"Lower Lake",
"Loyalton",
"Lucerne",
"Lynwood",
"Madera",
"Magalia",
"Malibu",
"Mammoth Lakes",
"Manhattan Beach",
"Manteca",
"Manton",
"Maricopa",
"Marina Del Rey",
"Marina",
"Mariposa",
"Martinez",
"Marysville",
"Maywood",
"Mc Farland",
"Mcarthur",
"Mccloud",
"Mckinleyville",
"Meadow Valley",
"Meadow Vista",
"Mecca",
"Mendocino",
"Mendota",
"Menlo Park",
"Mentone",
"Merced",
"Mi Wuk Village",
"Middletown",
"Mill Valley",
"Millbrae",
"Millville",
"Milpitas",
"Mira Loma",
"Miramonte",
"Mission Hills",
"Mission Viejo",
"Modesto",
"Mojave",
"Mokelumne Hill",
"Monrovia",
"Montague",
"Montara",
"Montclair",
"Monte Rio",
"Montebello",
"Monterey Park",
"Monterey",
"Moorpark",
"Moraga",
"Moreno Valley",
"Morgan Hill",
"Morongo Valley",
"Morro Bay",
"Moss Beach",
"Moss Landing",
"Mount Shasta",
"Mountain Ranch",
"Mountain View",
"Murphys",
"Murrieta",
"Napa",
"National City",
"Needles",
"Nevada City",
"Newark",
"Newman",
"Newport Beach",
"Newport Coast",
"Nice",
"Niland",
"Nipomo",
"Norco",
"North Highlands",
"Norwalk",
"Novato",
"Nuevo",
"Oak Park",
"Oak View",
"Oakdale",
"Oakhurst",
"Oakland",
"Oakley",
"Occidental",
"Oceano",
"Oceanside",
"Ocotillo",
"Ojai",
"Olivehurst",
"Ontario",
"Onyx",
"Orange Cove",
"Orange",
"Orangevale",
"Orinda",
"Orland",
"Orosi",
"Oroville",
"Oxnard",
"Pacific Grove",
"Pacifica",
"Palermo",
"Palm Desert",
"Palm Springs",
"Palmdale",
"Palo Alto",
"Palo Cedro",
"Palo Verde",
"Paradise",
"Paramount",
"Parlier",
"Pasadena",
"Patterson",
"Penn Valley",
"Perris",
"Petaluma",
"Pico Rivera",
"Piedmont",
"Pine Valley",
"Pinole",
"Piru",
"Pismo Beach",
"Pittsburg",
"Pixley",
"Placentia",
"Placerville",
"Planada",
"Pleasant Hill",
"Pleasanton",
"Plymouth",
"Point Arena",
"Point Reyes Station",
"Pollock Pines",
"Pomona",
"Port Costa",
"Port Hueneme",
"Porterville",
"Portola Valley",
"Portola",
"Poway",
"Quincy",
"Rail Road Flat",
"Ramona",
"Rancho Cordova",
"Rancho Cucamonga",
"Rancho Mirage",
"Rancho Palos Verdes",
"Rancho Santa Margarita",
"Red Bluff",
"Redding",
"Redlands",
"Redondo Beach",
"Redway",
"Redwood City",
"Reedley",
"Rialto",
"Richgrove",
"Richmond",
"Ridgecrest",
"Rio Dell",
"Rio Linda",
"Rio Vista",
"Ripon",
"Riverbank",
"Riverdale",
"Riverside",
"Rocklin",
"Rodeo",
"Rohnert Park",
"Rosamond",
"Rosemead",
"Roseville",
"Ross",
"Rowland Heights",
"Running Springs",
"Sacramento",
"Salida",
"Salinas",
"Salton City",
"San Andreas",
"San Anselmo",
"San Ardo",
"San Bernardino",
"San Bruno",
"San Carlos",
"San Clemente",
"San Diego",
"San Dimas",
"San Fernando",
"San Francisco",
"San Gabriel",
"San Geronimo",
"San Jacinto",
"San Joaquin",
"San Jose",
"San Juan Bautista",
"San Juan Capistrano",
"San Leandro",
"San Lorenzo",
"San Lucas",
"San Luis Obispo",
"San Marcos",
"San Marino",
"San Martin",
"San Mateo",
"San Miguel",
"San Pablo",
"San Rafael",
"San Ramon",
"Sanger",
"Santa Ana",
"Santa Barbara",
"Santa Clara",
"Santa Clarita",
"Santa Cruz",
"Santa Fe Springs",
"Santa Maria",
"Santa Monica",
"Santa Paula",
"Santa Rosa",
"Santa Ynez",
"Santee",
"Saratoga",
"Sausalito",
"Scotts Valley",
"Seal Beach",
"Seaside",
"Sebastopol",
"Seeley",
"Selma",
"Shafter",
"Shandon",
"Shasta Lake",
"Shaver Lake",
"Shingle Springs",
"Shingletown",
"Sierra Madre",
"Signal Hill",
"Simi Valley",
"Solana Beach",
"Soledad",
"Solvang",
"Sonoma",
"Sonora",
"Soquel",
"Soulsbyville",
"South Dos Palos",
"South El Monte",
"South Gate",
"South Lake Tahoe",
"South Pasadena",
"South San Francisco",
"Spreckels",
"Spring Valley",
"Springville",
"Squaw Valley",
"Stanford",
"Stanton",
"Stinson Beach",
"Stockton",
"Stratford",
"Strathmore",
"Strawberry",
"Suisun City",
"Summerland",
"Sun City",
"Sunnyvale",
"Sunol",
"Susanville",
"Sutter Creek",
"Sutter",
"Taft",
"Tahoe Vista",
"Talmage",
"Tehachapi",
"Tehama",
"Temecula",
"Temple City",
"Templeton",
"Terra Bella",
"Thousand Oaks",
"Thousand Palms",
"Three Rivers",
"Tipton",
"Tomales",
"Torrance",
"Tracy",
"Tranquillity",
"Traver",
"Trinidad",
"Truckee",
"Tulare",
"Tulelake",
"Tupman",
"Turlock",
"Tustin",
"Twain Harte",
"Twentynine Palms",
"Ukiah",
"Union City",
"Upland",
"Upper Lake",
"Vacaville",
"Vallecito",
"Vallejo",
"Valley Center",
"Valley Springs",
"Victorville",
"Villa Park",
"Visalia",
"Vista",
"Wallace",
"Walnut Creek",
"Walnut Grove",
"Walnut",
"Wasco",
"Waterford",
"Watsonville",
"Weaverville",
"Weed",
"Weldon",
"West Covina",
"West Hollywood",
"West Point",
"West Sacramento",
"Westlake Village",
"Westley",
"Westminster",
"Westmorland",
"Westwood",
"Wheatland",
"Whittier",
"Wildomar",
"Williams",
"Willits",
"Willow Creek",
"Willows",
"Wilton",
"Winchester",
"Windsor",
"Winterhaven",
"Winters",
"Winton",
"Wofford Heights",
"Woodacre",
"Woodlake",
"Woodland",
"Wrightwood",
"Yorba Linda",
"Yountville",
"Yreka",
"Yuba City",
"Yucaipa",
"Yucca Valley"]